name: imitator
channels:
  - defaults
dependencies:
  - pip=20.3
  - pip:
      - absl-py==1.0.0
      - antlr4-python3-runtime==4.8
      - appdirs==1.4.4
      - audioread==2.1.9
      - cachetools==5.0.0
      - certifi==2023.7.22
      - cffi==1.15.0
      - charset-normalizer==2.0.12
      - chumpy==0.70
      - click==8.0.4
      - cycler==0.11.0
      - decorator==5.1.1
      - filelock==3.6.0
      - fonttools==4.31.1
      - freetype-py==2.2.0
      - fsspec==2022.2.0
      - future==0.18.2
      - google-auth==2.6.2
      - google-auth-oauthlib==0.4.6
      - grpcio==1.44.0
      - huggingface-hub==0.4.0
      - idna==3.3
      - imageio==2.16.1
      - img2pdf==0.4.4
      - importlib-metadata==4.11.3
      - joblib==1.1.0
      - kiwisolver==1.4.0
      - librosa==0.9.1
      - llvmlite==0.38.0
      - lxml==4.8.0
      - markdown==3.3.6
      - matplotlib==3.5.1
      - matplotx==0.3.10
      - networkx==2.2
      - numba==0.55.1
      - oauthlib==3.2.0
      - omegaconf==2.0.0
      - opencv-python==4.5.5.64
      - packaging==21.3
      - pandas==1.3.5
      - pikepdf==5.1.3
      - pip==22.0.4
      - pooch==1.6.0
      - protobuf==3.19.4
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycparser==2.21
      - pyglet==1.4.0b1
      - pyopengl==3.1.0
      - pyparsing==3.0.7
      - pyrender==0.1.33
      - python-dateutil==2.8.2
      - pytorch-lightning==1.0.8
      - pytz==2022.1
      - pyyaml==6.0
      - pyzmq==22.3.0
      - regex==2022.3.15
      - requests==2.27.1
      - requests-oauthlib==1.3.1
      - resampy==0.2.2
      - rsa==4.8
      - sacremoses==0.0.49
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - soundfile==0.10.3.post1
      - tensorboard==2.8.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - threadpoolctl==3.1.0
      - tokenizers==0.11.6
      - tqdm==4.63.0
      - transformers==4.17.0
      - trimesh==3.10.5
      - typing-extensions==4.1.1
      - urllib3==1.26.9
      - werkzeug==2.0.3
      - zipp==3.7.0
